version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      Accept_EULA: "Y"
      SA_PASSWORD: "Pa55word!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
   